# Generated by Django 6.1 on 2026-08-18 00:00

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoUnivesp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobernome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=14)),
            ],
            managers=[
                ('obejtos', django.db.models.manager.Manager()),
            ],
        ),
    ]
