# Generated by Django 6.1 on 2026-08-18 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alunounivesp',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='alunounivesp',
            old_name='sobernome',
            new_name='sobrenome',
        ),
    ]
